apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: postgres-cluster-manual-20260406233029-20233
  namespace: default
spec:
  method: barmanObjectStore
  cluster:
    name: postgres-cluster
