apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: postgres-cluster-manual-20260411032409-36542
  namespace: default
spec:
  method: barmanObjectStore
  cluster:
    name: postgres-cluster
